---
services:
  stage:
    build:
      context: "."
    volumes:
      -
        source: app
        target: /app
        type: volume
  prod:
    depends_on:
      - stage
    image: "davidcaste/alpine-tomcat:latest"
    volumes:
      -
        source: app
        target: /opt/tomcat/webapps
        type: volume
    ports:
      - "8080:8080"
    command: /opt/tomcat/bin/catalina.sh run
version: '3.3'
volumes:
  app:
